project_id = "wnmfjueqkrvfnlvfgcvn"

[functions.process-csv]
verify_jwt = false

[functions.send-emails]
verify_jwt = false

[functions.process-campaign-pipeline]
verify_jwt = false

[functions.cache-logo]
verify_jwt = false

[functions.web-search]
verify_jwt = true
